version: "3"

# More info at https://github.com/linuxserver/Heimdall and https://heimdall.site/
services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    ports:
      - "81:80"
      - "444:443"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Zagreb'
    volumes:
      - /path/to/appdata/config:/config
    restart: unless-stopped