version: "3"

# More info at https://github.com/filebrowser/filebrowser and filebrowser.org
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    ports:
      - "80:80"
    volumes:
      - filebrowser-data:/srv
    restart: unless-stopped
    
volumes:
  filebrowser-data:
    driver_opts:
      type: cifs
      o: username=admin,password=password
      device: "//192.168.5.100/public"