version: '3'

# More info at https://github.com/louislam/uptime-kuma and uptime.kuma.pet
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  uptime-kuma:
