version: "3"

# More info at https://github.com/AdguardTeam/AdGuardHome and https://adguard.com/en/adguard-home/overview.html
services:
   adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 83:80/tcp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Zagreb'
    volumes:
      - ./conf:/conf
      - ./work:/work
    restart: unless-stopped