---
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 8053:53/tcp
      - 8053:53/udp
      - 8067:67/udp
      - 8068:68/tcp
      - 8068:68/udp
      - 1853:853/tcp
      - 8080:80/tcp
      - 3000:3000/tcp
    volumes:
      - /srv/adguard/config/AdGuard1/workdir:/opt/adguardhome/work
      - /srv/adguard/config/AdGuard1/confdir:/opt/adguardhome/conf
    restart: unless-stopped

# Note: 192.168.1.xxx is an example network, you must update all these to match your own.
version: "2.1"
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    mac_address: 00:12:90:90:19:09           # <-- Update
    cap_add:
      - NET_ADMIN
    networks:
      macvlan_NET:                      # <-- MACVlan Name no need to change, but do not exist previosly.
        ipv4_address: 192.168.1.3       # <-- Update
    volumes:
      - /srv/dev-disk-by-label-DATA/Data/dockers/adguard/Work:/opt/adguardhome/work
      - /srv/dev-disk-by-label-DATA/Data/dockers/adguard:/opt/adguardhome/conf
    restart: unless-stopped

networks:
  macvlan_NET:
    driver: macvlan
    driver_opts:
      parent: enp3s4f0                       # <- Update to match your NIC see your OMV WebGUI
    ipam:
      config:
        - subnet: 192.168.1.0/24            # <-- Update
          gateway: 192.168.1.1              # <-- Update
          ip_range: 192.168.1.2/28          # <-- Update